### PR TITLE
Change Package name to PDELib

### PR DESCRIPTION
**Pull request by vserge**
Change Package name to PDELib for requirements of late OpenModelica.

We are need to check against latest version of OpenModelica.
[Error-list-for-check.txt](https://github.com/modelica-3rdparty/PDELib/files/50247/Error-list-for-check.txt)

### CODE REVIEW

**Comment by dietmarw** [comment]
Thanks for the PR. However this library has currently no license so I can not really do anything about it and especially not change the name. You could try contacting the supervising Prof to ask for permission and especially why there is no license for this library available.

**Comment by vserge** [comment]
Dear Dietmar,

Today I received from supervising Prof Dr. François E. Cellier response to my e-mail:

> Dear Colleague:
> 
> The PDELib library had been created using Dymola 6.  When you load it into a more modern version of Dymola, the code gets automatically converted to the current Dymola format, which is compatible with OpenModelica.  PDELib was a student project [...].  By all means, update the code in any way or form that proves useful to you.  Choose a license format that suits your purpose.  I am happy with any license that grants free-of-cost access to the library.  The code should not get integrated into a commercial library (this would potentially create difficulties for me at my own institution).
>   Best regards
>         François

So I think we can setup OpenModelica license and update.

**Comment by dietmarw** [comment]
@vserge That's excellent news. 

The OpenModelica license is not really well suited for this since the author is not OSMC member so it does not make sense. Also FC says that he does not wish any license that allows inclusion into commercial products. This basically rules the Modelica Licenses out (which are BSD style). So I will put this library under the [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/) (which is similar LGPL but allows static linking).

Once I've done that you should update your PR to not change all the line endings from LF to CRLF (which is why the whole file was changed and not just the name part).

**Comment by dietmarw** [comment]
Also please rebase your PR on the master branch I'm going to create now since the lib goes from hibernation into active development :-)

**Pull request closed without merging**
